#!/bin/bash

ex=$1
file=$2
if  [[ $ex = "py" ]];
then
    if grep -q "#" $file;
    then
        echo "Yes from py"
    else
	echo "No from py"
    fi
else
    if grep -q "//" $file; 
    then
        echo "Yes"
    else
        echo "No" 
    fi 
fi
